<?php // Register Custom Post Type
add_action( 'init', function() {
	register_post_type( 'services', array(
        'labels' => array(
            'name' => 'services',
            'singular_name' => 'services',
            'menu_name' => 'services',
            'all_items' => 'All services',
            'edit_item' => 'Edit services',
            'view_item' => 'View services',
            'view_items' => 'View services',
            'add_new_item' => 'Add New services',
            'add_new' => 'Add New services',
            'new_item' => 'New services',
            'services_item_colon' => 'services:',
            'search_items' => 'Search services',
            'not_found' => 'No services found',
            'not_found_in_trash' => 'No services found in Trash',
            'archives' => 'services Archives',
            'attributes' => 'services Attributes',
            'insert_into_item' => 'Insert into services',
            'uploaded_to_this_item' => 'Uploaded to this services',
            'filter_items_list' => 'Filter services list',
            'filter_by_date' => 'Filter services by date',
            'items_list_navigation' => 'services list navigation',
            'items_list' => 'services list',
            'item_published' => 'services published.',
            'item_published_privately' => 'services published privately.',
            'item_reverted_to_draft' => 'services reverted to draft.',
            'item_scheduled' => 'services scheduled.',
            'item_updated' => 'services updated.',
            'item_link' => 'services Link',
            'item_link_description' => 'A link to a services.',
        ),
        'public' => true,
        'has_archive' => true,
        'hierarchical' => true,
        'show_in_rest' => true,
        'menu_icon' => 'dashicons-admin-multisite',
        'supports' => array(
            0 => 'title',
            1 => 'editor',
            2 => 'excerpt',
            3 => 'thumbnail',
            4 => 'custom-fields',
        ),
        'delete_with_user' => false,
    ));
});
?>
