<?php
add_action('acf/include_fields', function () {
    if (! function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'block_faq_accordions',
        'title' => 'faq accordions',
        'fields' => array(
            array(
                'key' => 'field_6821815594b111',
                'label' => 'Block ID',
                'name' => 'block_id',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),

            array(
                'key' => 'field_26821815594bd11',
                'label' => 'Number',
                'name' => 'number',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),

            array(
                'key' => 'field_2682181d5594ba11',
                'label' => 'Title',
                'name' => 'title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6809075c9331d6',
                'label' => 'Description',
                'name' => 'description',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'rows' => 8,
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_2682181d5594bas11',
                'label' => 'Sub Title',
                'name' => 'sub_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),

            array(
                'key' => 'field_board_cards_qwe',
                'label' => 'Faq Accordions',
                'name' => 'faq_accordions',
                'type' => 'repeater',
                'instructions' => 'Add cards to the board.',
                'required' => 0,
                'layout' => 'vertical',
                'button_label' => 'Add Accordion',

                'sub_fields' => array(
                    array(
                        'key' => 'field_card_title_213122',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_682s17bee8b0b2aa',
                        'label' => 'Content',
                        'name' => 'timeline_list',
                        'aria-label' => '',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'pagination' => 0,
                        'min' => 0,
                        'max' => 0,
                        'collapsed' => '',
                        'button_label' => 'Add Item',
                        'rows_per_page' => 20,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_68s217c123sa0f8b0bb',
                                'label' => 'Time line Description',
                                'name' => 'description',
                                'aria-label' => '',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'allow_in_bindings' => 0,
                                'rows' => '',
                                'placeholder' => '',
                                'new_lines' => '',
                                'parent_repeater' => 'field_682s17bee8b0b2aa',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_26asd821815594bd11',
                'label' => 'See Others Title',
                'name' => 'see_others_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'ifeld_explore_others_123',
                'label' => 'Explore Others',
                'name' => 'explore_others',
                'type' => 'repeater',
                'instructions' => 'Add links to others.',
                'required' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_explore_others_link',
                        'label' => 'Link',
                        'name' => 'link',
                        'type' => 'link',
                        'instructions' => 'Add a link.',
                        'required' => 0,
                    ),

                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/faq-accordions',
                ),
            ),
        ),
    ));
});
