<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
        'key' => 'group_68ac2c5c69a13',
        'title' => 'Locations',
        'fields' => array(
            array(
                'key' => 'field_68ac2c5cf55d8',
                'label' => 'Heading',
                'name' => 'heading',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '75',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_68ac2cf5f55da',
                'label' => 'Pin',
                'name' => 'pin',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'allow_in_bindings' => 0,
                'preview_size' => 'thumbnail',
            ),
            array(
                'key' => 'field_68ac2c87f55d9',
                'label' => 'Locations',
                'name' => 'locations',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Add Location',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_68ac2d91f55db',
                        'label' => 'Country',
                        'name' => 'country',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'United Arab Emirates' => 'United Arab Emirates',
                            'Afghanistan' => 'Afghanistan',
                            'Albania' => 'Albania',
                            'Armenia' => 'Armenia',
                            'Angola' => 'Angola',
                            'Argentina' => 'Argentina',
                            'Austria' => 'Austria',
                            'Australia' => 'Australia',
                            'Azerbaijan' => 'Azerbaijan',
                            'Bosnia and Herzegovina' => 'Bosnia and Herzegovina',
                            'Bangladesh' => 'Bangladesh',
                            'Belgium' => 'Belgium',
                            'Burkina Faso' => 'Burkina Faso',
                            'Bulgaria' => 'Bulgaria',
                            'Burundi' => 'Burundi',
                            'Benin' => 'Benin',
                            'Brunei Darussalam' => 'Brunei Darussalam',
                            'Bolivia' => 'Bolivia',
                            'Brazil' => 'Brazil',
                            'Bahamas' => 'Bahamas',
                            'Bhutan' => 'Bhutan',
                            'Botswana' => 'Botswana',
                            'Belarus' => 'Belarus',
                            'Belize' => 'Belize',
                            'Canada' => 'Canada',
                            'Democratic Republic of Congo' => 'Democratic Republic of Congo',
                            'Central African Republic' => 'Central African Republic',
                            'Republic of Congo' => 'Republic of Congo',
                            'Switzerland' => 'Switzerland',
                            'Côte d\'Ivoire' => 'Côte d\'Ivoire',
                            'Chile' => 'Chile',
                            'Cameroon' => 'Cameroon',
                            'China' => 'China',
                            'Colombia' => 'Colombia',
                            'Costa Rica' => 'Costa Rica',
                            'Cuba' => 'Cuba',
                            'Cyprus' => 'Cyprus',
                            'Czechia' => 'Czechia',
                            'Germany' => 'Germany',
                            'Djibouti' => 'Djibouti',
                            'Denmark' => 'Denmark',
                            'Dominican Republic' => 'Dominican Republic',
                            'Algeria' => 'Algeria',
                            'Ecuador' => 'Ecuador',
                            'Estonia' => 'Estonia',
                            'Egypt' => 'Egypt',
                            'Western Sahara' => 'Western Sahara',
                            'Eritrea' => 'Eritrea',
                            'Spain' => 'Spain',
                            'Ethiopia' => 'Ethiopia',
                            'Falkland Islands' => 'Falkland Islands',
                            'Finland' => 'Finland',
                            'Fiji' => 'Fiji',
                            'France' => 'France',
                            'Gabon' => 'Gabon',
                            'United Kingdom' => 'United Kingdom',
                            'Georgia' => 'Georgia',
                            'French Guiana' => 'French Guiana',
                            'Ghana' => 'Ghana',
                            'Greenland' => 'Greenland',
                            'Gambia' => 'Gambia',
                            'Guinea' => 'Guinea',
                            'Equatorial Guinea' => 'Equatorial Guinea',
                            'Greece' => 'Greece',
                            'Guatemala' => 'Guatemala',
                            'Guinea-Bissau' => 'Guinea-Bissau',
                            'Guyana' => 'Guyana',
                            'Honduras' => 'Honduras',
                            'Croatia' => 'Croatia',
                            'Haiti' => 'Haiti',
                            'Hungary' => 'Hungary',
                            'Indonesia' => 'Indonesia',
                            'Ireland' => 'Ireland',
                            'Israel' => 'Israel',
                            'India' => 'India',
                            'Iraq' => 'Iraq',
                            'Iran' => 'Iran',
                            'Iceland' => 'Iceland',
                            'Italy' => 'Italy',
                            'Jamaica' => 'Jamaica',
                            'Jordan' => 'Jordan',
                            'Japan' => 'Japan',
                            'Kenya' => 'Kenya',
                            'Kyrgyzstan' => 'Kyrgyzstan',
                            'Cambodia' => 'Cambodia',
                            'North Korea' => 'North Korea',
                            'South Korea' => 'South Korea',
                            'Kosovo' => 'Kosovo',
                            'Kuwait' => 'Kuwait',
                            'Kazakhstan' => 'Kazakhstan',
                            'Lao People\'s Democratic Republic' => 'Lao People\'s Democratic Republic',
                            'Lebanon' => 'Lebanon',
                            'Sri Lanka' => 'Sri Lanka',
                            'Liberia' => 'Liberia',
                            'Lesotho' => 'Lesotho',
                            'Lithuania' => 'Lithuania',
                            'Luxembourg' => 'Luxembourg',
                            'Latvia' => 'Latvia',
                            'Libya' => 'Libya',
                            'Morocco' => 'Morocco',
                            'Moldova' => 'Moldova',
                            'Montenegro' => 'Montenegro',
                            'Madagascar' => 'Madagascar',
                            'Macedonia' => 'Macedonia',
                            'Mali' => 'Mali',
                            'Myanmar' => 'Myanmar',
                            'Mongolia' => 'Mongolia',
                            'Mauritania' => 'Mauritania',
                            'Malawi' => 'Malawi',
                            'Mexico' => 'Mexico',
                            'Malaysia' => 'Malaysia',
                            'Mozambique' => 'Mozambique',
                            'Namibia' => 'Namibia',
                            'New Caledonia' => 'New Caledonia',
                            'Niger' => 'Niger',
                            'Nigeria' => 'Nigeria',
                            'Nicaragua' => 'Nicaragua',
                            'Netherlands' => 'Netherlands',
                            'Norway' => 'Norway',
                            'Nepal' => 'Nepal',
                            'New Zealand' => 'New Zealand',
                            'Oman' => 'Oman',
                            'Panama' => 'Panama',
                            'Peru' => 'Peru',
                            'Papua New Guinea' => 'Papua New Guinea',
                            'Philippines' => 'Philippines',
                            'Poland' => 'Poland',
                            'Pakistan' => 'Pakistan',
                            'Puerto Rico' => 'Puerto Rico',
                            'Palestinian Territories' => 'Palestinian Territories',
                            'Portugal' => 'Portugal',
                            'Paraguay' => 'Paraguay',
                            'Qatar' => 'Qatar',
                            'Romania' => 'Romania',
                            'Serbia' => 'Serbia',
                            'Russia' => 'Russia',
                            'Rwanda' => 'Rwanda',
                            'Saudi Arabia' => 'Saudi Arabia',
                            'Solomon Islands' => 'Solomon Islands',
                            'Sudan' => 'Sudan',
                            'Sweden' => 'Sweden',
                            'Slovenia' => 'Slovenia',
                            'Svalbard and Jan Mayen' => 'Svalbard and Jan Mayen',
                            'Slovakia' => 'Slovakia',
                            'Sierra Leone' => 'Sierra Leone',
                            'Senegal' => 'Senegal',
                            'Somalia' => 'Somalia',
                            'Suriname' => 'Suriname',
                            'South Sudan' => 'South Sudan',
                            'El Salvador' => 'El Salvador',
                            'Syria' => 'Syria',
                            'Swaziland' => 'Swaziland',
                            'Chad' => 'Chad',
                            'French Southern and Antarctic Lands' => 'French Southern and Antarctic Lands',
                            'Togo' => 'Togo',
                            'Thailand' => 'Thailand',
                            'Tajikistan' => 'Tajikistan',
                            'Timor-Leste' => 'Timor-Leste',
                            'Turkmenistan' => 'Turkmenistan',
                            'Tunisia' => 'Tunisia',
                            'Turkey' => 'Turkey',
                            'Trinidad and Tobago' => 'Trinidad and Tobago',
                            'Taiwan' => 'Taiwan',
                            'Tanzania' => 'Tanzania',
                            'Ukraine' => 'Ukraine',
                            'Uganda' => 'Uganda',
                            'United States' => 'United States',
                            'Uruguay' => 'Uruguay',
                            'Uzbekistan' => 'Uzbekistan',
                            'Venezuela' => 'Venezuela',
                            'Vietnam' => 'Vietnam',
                            'Vanuatu' => 'Vanuatu',
                            'Yemen' => 'Yemen',
                            'South Africa' => 'South Africa',
                            'Zambia' => 'Zambia',
                            'Zimbabwe' => 'Zimbabwe',
                        ),
                        'default_value' => false,
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 1,
                        'ui' => 1,
                        'ajax' => 1,
                        'placeholder' => '',
                        'parent_repeater' => 'field_68ac2c87f55d9',
                    ),
                    array(
                        'key' => 'field_68ac67a1acfc0',
                        'label' => 'Label',
                        'name' => 'label',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_68ac2c87f55d9',
                    ),
                    array(
                        'key' => 'field_68ac32ff6fdb7',
                        'label' => 'Content',
                        'name' => 'content',
                        'aria-label' => '',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'allow_in_bindings' => 0,
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                        'parent_repeater' => 'field_68ac2c87f55d9',
                    ),
                    array(
                        'key' => 'field_68ac32ed6fdb6',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'allow_in_bindings' => 0,
                        'preview_size' => 'medium',
                        'parent_repeater' => 'field_68ac2c87f55d9',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/locations',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});
?>
