<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_68235393adb1d',
	'title' => 'Posts sec',
    'fields' => array(
        array(
            'key' => 'field_posts_680fh90ba6452',
            'label' => 'Sub Heading',
            'name' => 'sub_heading',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_posts_68090599ba5c2',
            'label' => 'Heading',
            'name' => 'heading',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_posts_68090599ba5da',
            'label' => 'Description',
            'name' => 'description',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'rows' => 4,
            'placeholder' => '',
            'new_lines' => '',
        ),
        array(
            'key' => 'field_posts_680f66f2a87c8',
            'label' => 'Image',
            'name' => 'image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 0,
            'preview_size' => 'medium',
        ),
        array(
            'key' => 'field_posts_68090599ba5ea',
            'label' => 'Posts Type',
            'name' => 'posts_type',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'latest' => 'Latest',
                'select' => 'Select',
            ),
            'default_value' => 'latest',
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'allow_in_bindings' => 0,
            'layout' => 'vertical',
            'save_other_choice' => 0,
        ),
        array(
            'key' => 'field_posts_68090599ba5f8',
            'label' => 'Posts',
            'name' => 'posts',
            'aria-label' => '',
            'type' => 'relationship',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_posts_68090599ba5ea',
                        'operator' => '==',
                        'value' => 'select',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'post',
            ),
            'post_status' => array(
                0 => 'publish',
            ),
            'taxonomy' => '',
            'filters' => '',
            'return_format' => 'object',
            'min' => '',
            'max' => '',
            'allow_in_bindings' => 0,
            'elements' => array(
                0 => 'featured_image',
            ),
            'bidirectional' => 0,
            'bidirectional_target' => array(
            ),
        ),
        array(
            'key' => 'field_posts_6809061a8d89c',
            'label' => 'Button',
            'name' => 'button',
            'aria-label' => '',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'allow_in_bindings' => 0,
        ),
    ),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/posts-section',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );


?>
